dataset:
  name: PDE_KS
  pair_id: [9]
model:
  activation: tanh
  branch_layers: 2
  epochs: 10000
  initialization: He normal
  lag: 27
  learning_rate: 0.0032958541236063933
  method: constant
  name: DeepONet
  neurons: 124
  optimizer: L-BFGS
  seed: 0
  trunk_layers: 3