dataset:
  name: ODE_Lorenz
  pair_id: [1]
model:
  activation: tanh
  branch_layers: 4
  epochs: 10000
  initialization: He normal
  lag: 29
  learning_rate: 0.03456282864713975
  method: constant
  name: DeepONet
  neurons: 441
  optimizer: L-BFGS
  seed: 0
  trunk_layers: 3
