dataset:
  name: ODE_Lorenz
  pair_id: [2]
model:
  activation: relu
  branch_layers: 1
  epochs: 10000
  initialization: Glorot normal
  lag: 9
  learning_rate: 0.00010390793714039815
  method: constant
  name: DeepONet
  neurons: 67
  optimizer: L-BFGS
  seed: 0
  trunk_layers: 3
